@echo off
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
msg * https://www.youtube.com/@Berferil
:loop
start cmp
goto loop